Fix create issue with image
ConnectAI-E/GitMaya pull request #151
Opened 2024-01-25 11:14 UTC by freeziyou

- [ ] 修复 GitHub 新建带图片的 Issue 时飞书无法展示卡片问题

2024-01-25 11:16 UTC, freeziyou commented on server/tasks/lark/issue.py
> +            # TODO 判断是否有图片
从github回复issue评论还没处理，明天加上

2024-01-25 11:53 UTC, lloydzhou requested changes

2024-01-25 11:53 UTC, lloydzhou commented on pdm.lock
> +    "greenlet!=0.4.17; platform_machine == \"win32\" or platform_machine == \"WIN32\" or platform_machine == \"AMD64\" or platform_machine == \"amd64\" or platform_machine == \"x86_64\" or platform_m
不要提交这些东西把你的win32的提交上来了

2024-01-25 11:53 UTC, lloydzhou commented on pdm.lock
> +    "greenlet!=0.4.17; platform_machine == \"win32\" or platform_machine == \"WIN32\" or platform_machine == \"AMD64\" or platform_machine == \"amd64\" or platform_machine == \"x86_64\" or platform_m
而且，本身没有更改库版本，不应该提交这个文件

2024-01-25 11:53 UTC, lloydzhou commented on server/utils/lark/base.py
> +    logging.info(messages)
这个文件没有import logging

2024-01-25 11:53 UTC, lloydzhou commented on server/utils/lark/base.py
> +def desc_to_feishu_message(desc):
飞书FeishuMessageMarkdown 支持![image_name](image_key) 格式，没必要换成FeishuMessageImage

2024-01-25 11:53 UTC, lloydzhou commented on server/utils/lark/base.py
> +def desc_to_feishu_message(desc):
https://open.feishu.cn/document/common-capabilities/message-card/message-cards-content/using-markdown-tags

2024-01-25 11:53 UTC, lloydzhou commented on server/utils/lark/base.py
> +def desc_to_feishu_message(desc):
![image](https://github.com/ConnectAI-E/GitMaya/assets/1826685/77161842-df6a-4f88-8eff-06e30e979aa7)

2024-01-25 11:53 UTC, lloydzhou commented on server/utils/utils.py
> +    bot, _ = get_bot_by_application_id(application_id)
这个函数，最好是直接传 bot对象，而不是传application_id

2024-01-25 11:53 UTC, lloydzhou commented on server/tasks/lark/issue.py
> +def replace_images_and_split_text(text, bot):
这里的变量名字，看调用的地方传过来是application_id但是，名字是bot...

2024-01-25 13:52 UTC, jingfelix commented on pdm.lock
> +    "greenlet!=0.4.17; platform_machine == \"win32\" or platform_machine == \"WIN32\" or platform_machine == \"AMD64\" or platform_machine == \"amd64\" or platform_machine == \"x86_64\" or platform_m
看起来这里只修改了顺序……不过在不修改依赖的情况下， `pdm.lock` 不改也是可以过检查的，非必须提交

2024-01-26 02:44 UTC, freeziyou commented on server/tasks/lark/issue.py
> +            # TODO 判断是否有图片
![image](https://github.com/ConnectAI-E/GitMaya/assets/33377207/85ad4e23-9c7f-4780-84f0-8f74979981ad)
sdk那边还需要加个富文本FeishuPostMessage类，msg_type为post，能够支持一条消息同时发图片和文字 @lloydzhou

2024-01-26 04:49 UTC, lloydzhou commented on server/tasks/lark/issue.py
> +            # TODO 判断是否有图片
我们现在需要发post消息吗？

2024-01-26 04:49 UTC, lloydzhou commented on server/utils/utils.py
> +def upload_image(url, bot):
需要给这个从github url转换image_key的函数加上一个缓存。

1. 直接自己操作redis写一个缓存
2. 去manager-serve/server/core.redisdb里面把那个stalecache移过来，放到utils/redis.py，直接加上装饰器就好了

2024-01-26 05:27 UTC, freeziyou commented on server/utils/utils.py
> +def upload_image(url, bot):
发送的消息中如果带有图片和文字等多种形式（包括@），就需要发post

2024-01-26 07:29 UTC, lloydzhou commented
![](img_v3_027f_346befc4-453e-414b-bdc7-f8392bce2bdg)  
单个pr尽量只完成一件事情

2024-01-29 11:26 UTC, freeziyou reviewed
@lloydzhou 这里支持了github issue 评论中有图片，at还没做，等github和飞书映射写好了再改

2024-01-30 05:29 UTC, lloydzhou requested changes

2024-01-30 05:29 UTC, lloydzhou commented on server/tasks/lark/issue.py
> +    elements = re.split("\n", comment)
更换使用re.sub

2024-01-30 10:20 UTC, merged

2024-01-30 10:23 UTC, lloydzhou commented
close #101